name: Setup
description: Checkout repo and install dependencies

inputs:
  fetch-depth:
    description: Fetch depth to pass to checkout
    default: '2'
  install-cloudsmith-cli:
    description: Fetch depth to pass to checkout
    default: 'false'
  use-git-lfs:
    description: Whether to install and activate Git LFS
    default: 'false'
  run-checkout:
    description: Whether to check out code before setup. This is useful to disable when running composite actions inside a workflow
    default: 'true'

runs:
  using: composite
  steps:
    - name: Verify Inputs - Fetch depth must be 2 or 0 so commit/push does not overwrite entire history
      shell: bash
      run: |
        if [ ${{ inputs.fetch-depth }} == "1" ]; then
          echo "fetch-depth must never be 1 so that commit/push does not overwrite entire branch history. "
          exit 1
         else
          echo "fetch-depth is a valid value of ${{ inputs.fetch-depth }}"
        fi

    - name: Checkout
      if: ${{ inputs.run-checkout == 'true' }}
      uses: actions/checkout@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        # This ref is required for the mplat cli to be able to validate the commit message (validate-commit) and PR labels on the branch (validate-labels)
        #   otherwise the checkout pulls the merge commit a detached head state
        ref: ${{ github.event.pull_request.head.ref }}
        # Fetch depth here is important. (Fetching just 1 commit would overwrite the whole history when force ammending a commit)
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.use-git-lfs }}

    - name: Checkout LFS objects
      if: ${{ inputs.use-git-lfs == 'true' }}
      shell: bash
      run: git lfs checkout

    - name: Install Cloudsmith CLI
      if: ${{ inputs.install-cloudsmith-cli == 'true' }}
      uses: alkami/github_actions/.github/composites/install_cloudsmith_cli@main

    # Authenticates git with the github credentials. Allows us to fetch repositories/push etc
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        global: false
        token: ${{ env.GITHUB_TOKEN }}

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ env.FLUTTER_VERSION }}-flutter

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Authorize Cloudsmith
      shell: bash
      run: echo ${{ env.CLOUDSMITH_API_KEY }} | dart pub token add https://dart.cloudsmith.io/alkami/flutter/

    # Updates the git config to allow us to use https github requests (useful when installing mplat directly from github)
    # - name: Git Config Update
    #   shell: bash
    #   run: git config --global url."https://x-token-auth:${{ env.GITHUB_TOKEN }}@github.com".InsteadOf https://github.com
    
    - name: Activate mplat
      shell: bash
      run: |
        dart pub global activate mplat \
          --hosted-url https://dart.cloudsmith.io/alkami/flutter/
      # dart pub global activate --source git https://github.com/Alkami/mobile_platform_cli.git --git-ref feat/mskolnick/DEV-156308-auto-version-on-publish