env:
  FLUTTER_VERSION: 3.29.3
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  workflow_call:

jobs:
  build:
    name: Respond to app-foundation tag - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Respond to a tag in app-foundation by doing the following

          1. Tag this commit with an "app-foundation-\<version\>" eg: "app-foundation-4000.0.0"

          A diagram of the flow can be found here: https://confluence.alkami.com/x/3jdME
          "

      - name: Setup Alkami Environment 
        uses: alkami/github_actions/.github/composites/environment_setup@main

      - name: Tag package with app-foundation version app-foundation-v${{ inputs.app_foundation_version }}
        # This app_foundation_version param is passed in by the GH action which triggered this flow in app-foundation
        run: |
          tag_name=app-foundation-v${{ inputs.app_foundation_version }}
          echo "tag_name: $tag_name"
          git tag $tag_name
          git push origin $tag_name
