env:
  FLUTTER_VERSION: 3.7.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  workflow_call:

jobs:
  build:
    name: Validate PR Labels - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Command Summary:
          Validates that the PR does not contain any prohibited labels such as 'DO NOT MERGE'
          The prohibited labels can be modified in the mplat.yaml file of this repository
          "

      - name: Setup Mplat
        uses: alkami/github_actions/.github/composites/mplat_setup@main

      - name: Validate PR Labels
        run: mplat validate-labels
