env:
  FLUTTER_VERSION: 3.29.3
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  workflow_call:

jobs:
  build:
    name: Respond to app-foundation release branch - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Respond to a release branch being created in app-foundation by doing the following

          1. Create a hotfix branch from this commit in case this version needs to be hotfixed in the future

          A diagram of the flow can be found here: https://confluence.alkami.com/x/3jdME
          "

      - name: Setup Alkami Environment 
        uses: alkami/github_actions/.github/composites/environment_setup@main

      - name: Make a hotfix branch in this package with an updated version
        run: mplat admin branch package-hotfix-branch

      - name: Commit and push changes
        run: |
          echo "NOTE* If you amend the commit and force push you must have a checkout fetch depth of 0 or at least 2. Otherwise the entire git history will be re-written."
          git config user.name "alkami-svc-github-circle"
          git config user.email "alkami-svc-github-circle@users.noreply.github.com"
          git add -A
          git commit -m "switch to hotfix versioning for hotfix branch"
          git config push.autoSetupRemote true
          git push -u
