env:
  FLUTTER_VERSION: 3.7.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  workflow_call:

jobs:
  build:
    name: Respond to app-foundation tag - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Respond to a tag in app-foundation by doing the following

          1. Tag this commit with an "app-foundation-\<version\>" eg: "app-foundation-4000.0.0"
          2. Create a hotfix branch from this commit in case this version needs to be hotfixed in the future

          A diagram of the flow can be found here: https://confluence.alkami.com/x/3jdME
          "

      - name: Setup Alkami Environment 
        uses: alkami/github_actions/.github/composites/environment_setup@main

      - name: Tag package with app-foundation version app-foundation-v${{ inputs.app_foundation_version }}
        # This app_foundation_version param is passed in by the GH action which triggered this flow in app-foundation
        run: |
          tag_name=app-foundation-v${{ inputs.app_foundation_version }}
          echo "tag_name: $tag_name"
          git tag $tag_name
          git push origin $tag_name

      - name: Make a hotfix branch in this package with an updated version
        run: mplat admin branch package-hotfix-branch

      - name: Commit changes
        run: |
          echo "NOTE* If you amend the commit and force push you must have a checkout fetch depth of 0 or at least 2. Otherwise the entire git history will be re-written."
          git config user.name "alkami-svc-github-circle"
          git config user.email "alkami-svc-github-circle@users.noreply.github.com"
          git add -A
          git commit -m "switch to hotfix versioning for hotfix branch"
          git push -u

      - name: Set git config to auto-push remote in next step
        run: git config push.autoSetupRemote true
