env:
  FLUTTER_VERSION: 3.29.3
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  workflow_call:

jobs:
  build:
    name: Validate PR is Ready for Merge - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Validates Pull Request is ready for merge
          Calls into mplat CLI. For more info, see docs on mplat validate-pr here: https://github.com/Alkami/mobile_platform_cli/blob/main/HELP_DOCS.g.md#validate-pr
          NOTE* It is recommended to run this validation on your local machine before putting in your PR
            It is much faster to debug issues when running locally
            To debug locally, run: `mplat validate-pr`
          "

      - name: Setup Alkami Environment 
        uses: alkami/github_actions/.github/composites/environment_setup@main

      - name: Pub get
        run: flutter pub get

      - name: Validate PR is ready
        run: mplat validate-pr
