env:
  flutter_version: 3.7.3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:

jobs:
  build:
    name: Validate PR is Ready for Merge - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Validates Pull Request is ready for merge
          Calls into mplat CLI. For more info, see docs on mplat validate-pr here: https://github.com/Alkami/mobile_platform_cli/blob/main/HELP_DOCS.g.md#validate-pr
          NOTE* It is recommended to run this validation on your local machine before putting in your PR
            It is much faster to debug issues when running locally
            To debug locally, run: `mplat validate-pr`
          "
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          # This ref is required for the mplat cli to be able to validate the commit message
          #   otherwise the checkout pulls the merge commit a detached head state
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: false
          token: '${{ secrets.GH_ACTIONS_PAT }}'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ env.flutter_version }}-flutter

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true

      - name: Authorize Cloudsmith
        run: echo ${{ secrets.CLOUDSMITH_API_KEY }} | dart pub token add https://dart.cloudsmith.io/alkami/flutter/

      - name: Git Config Update
        run: git config --global url."https://x-token-auth:${{ secrets.GH_ACTIONS_PAT }}@github.com".InsteadOf https://github.com
      
      - name: Activate mplat
        run: |
          dart pub global activate --source git https://github.com/Alkami/mobile_platform_cli.git --git-ref feat/mskolnick/DEV-156308-auto-version-on-publish
        # dart pub global activate mplat \
        #   --hosted-url https://dart.cloudsmith.io/alkami/flutter/

      - name: Pub get
        run: flutter pub get

      - name: Validate PR is ready
        run: mplat validate-pr
