env:
  FLUTTER_VERSION: 3.7.3
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  # Using the GH_ACTIONS_PAT so that it can bypass branch protection PR requirement
  # Info of how this works: https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-actionv
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}

on:
  push:
    branches:
      - test_branch_mskolnick-4

jobs:
  build:
    # *** This if check is very important ***
    # We use this to make sure that we do not get into an infinite loop of workflow runs triggered by a push.
    if: github.event.pusher.name != 'alkami-svc-github-circle'
    name: Publish Package - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 2
    
      - name: Update Changelog
        run: touch test_file.md

      - name: Commit and push changes
        # The --author in the commit is so that the commit still shows up as the author who merged the code
        # otherwise all of our commits would show alkami-svc-github-circle as the author
        run: |
          echo "NOTE* If you amend the commit and force push you must have a checkout fetch depth of 0 or at least 2. Otherwise the entire git history will be re-written."
          git config user.name "alkami-svc-github-circle"
          git config user.email "alkami-svc-github-circle@users.noreply.github.com"
          git add -A
          git commit -v --no-edit --amend --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push --force

