env:
  FLUTTER_VERSION: 3.7.3
  GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

on:
  push:
    branches:
      - main
      - hotfix/**
      - test_branch_mskolnick

jobs:
  build:
    # *** This if check is very important ***
    # We use this to make sure that we do not get into an infinite loop of workflow runs triggered by a push.
    if: github.event.pusher.name != 'alkami-svc-github-circle'
    name: Validate PR is Ready for Merge - Reusable
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print Command Summary
        run: |
          echo "
          Validates Pull Request is ready for merge
          Calls into mplat CLI. For more info, see docs on mplat validate-pr here: https://github.com/Alkami/mobile_platform_cli/blob/main/HELP_DOCS.g.md#validate-pr
          NOTE* It is recommended to run this validation on your local machine before putting in your PR
            It is much faster to debug issues when running locally
            To debug locally, run: `mplat validate-pr`
          "

      - name: Setup Environment
        uses: alkami/github_actions/.github/composites/environment_setup@test_branch_mskolnick

      - name: Create a file to commit
        run: touch test_file.md

      - name: Commit changes
        run: |
          git config user.name "alkami-svc-github-circle"
          git config user.email "alkami-svc-github-circle@users.noreply.github.com"
          git add -A
          git commit -v --no-edit --amend

      # - name: Get last commit message for next step
      #   id: last-commit-message
      #   run: |
      #     echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      # - name: Amend the current commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: ${{ steps.last-commit-message.outputs.msg }}
      #     commit_options: --amend --no-edit
      #     push_options: --force
      #     skip_fetch: true

